name: Build

on: [push, pull_request]

jobs:
  build:
    name: Run Black
    runs-on: ubuntu-18.04
    steps:
    - name: Gradual Black Formatter
      # You may pin to the exact commit or the version.
      # uses: rocioar/gradual-black-formatter@3734d1eaff8e23012583cc599b2ea28e417b6b5f
      uses: rocioar/gradual-black-formatter@v2
      with:
        # Number of files to which the black formatter should be applied at once.
        number_of_files: 10
